[versions]
# build tools
java = "21"
kotlin = "1.9.24"
ktlint = "1.2.0"
jacoco = "0.8.11"
# dependencies
mongodb = "5.1.4"
logback = "1.5.8"
r2dbc = "1.0.0.RELEASE"
coroutines = "1.9.0"
# test dependencies
junit = "5.11.0"
spock = "2.4-M4-groovy-4.0"
testcontainers = "1.20.1"

[libraries]
# build tools
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "12.1.0" }
gradle-nexusPublish = { module = "io.github.gradle-nexus:publish-plugin", version = "1.3.0" }
# dependencies
reactor-core = { module = "io.projectreactor:reactor-core", version = "3.6.10" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version = "3.1.9" }
mongodb-core = { module = "org.mongodb:mongodb-driver-core", version.ref = "mongodb" }
mongodb-reactivestreams = { module = "org.mongodb:mongodb-driver-reactivestreams", version.ref = "mongodb" }
mongodb-coroutine = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongodb" }
mongodb-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.16" }
logback-core = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
postgresql = { module = "org.postgresql:postgresql", version = "42.7.4" }
mysql = { module = "com.mysql:mysql-connector-j", version = "8.4.0" }
r2dbc-spi = { module = "io.r2dbc:r2dbc-spi", version.ref = "r2dbc" }
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version.ref = "r2dbc" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version = "1.0.5.RELEASE" }
r2dbc-mysql = { module = "io.asyncer:r2dbc-mysql", version = "1.3.0" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "coroutines" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
# test dependencies
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }
hikaricp = { module = "com.zaxxer:HikariCP", version = "5.1.0" }
testcontainers-mongodb = { module = "org.testcontainers:mongodb", version.ref = "testcontainers" }
testcontainers-mysql = { module = "org.testcontainers:mysql", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
jsonassert = { module = "org.skyscreamer:jsonassert", version = "1.5.3" }
awaitility = { module = "org.awaitility:awaitility", version = "4.2.2" }
